-- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 11:10:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clinicadental2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinicadental2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinicadental2` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `clinicadental2` ;

-- -----------------------------------------------------
-- Table `clinicadental2`.`tbl_Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental2`.`tbl_Pacientes` (
  `id_Pacientes` INT NOT NULL AUTO_INCREMENT,
  `nombre_Pacientes` VARCHAR(45) NOT NULL,
  `direccion_Pacientes` VARCHAR(45) NOT NULL,
  `telefonoCasa` VARCHAR(12) NULL,
  `telefonoCel` VARCHAR(12) NULL,
  `fechaRegistro` DATE NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `ocupacion` VARCHAR(45) NULL,
  `recomendadoPor` VARCHAR(45) NULL,
  `personaResponsable` VARCHAR(40) NULL,
  `numeroRecomendaciones` INT NULL,
  `direccionResponsable` VARCHAR(45) NULL,
  `medicoPersonal` VARCHAR(45) NULL,
  `telefonoMedico` VARCHAR(45) NULL,
  `fotografias` VARCHAR(254) NULL,
  `estadoPaciente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Pacientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicadental2`.`tbl_Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental2`.`tbl_Citas` (
  `id_Citas` INT NOT NULL AUTO_INCREMENT,
  `id_Pacientes` INT NOT NULL,
  `fechaProgramada` DATE NOT NULL,
  `hora` TIME(6) NOT NULL,
  `descripcionCita` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Citas`),
  INDEX `fk_tbl_Citas_tbl_Pacientes_idx` (`id_Pacientes` ASC),
  CONSTRAINT `fk_tbl_Citas_tbl_Pacientes`
    FOREIGN KEY (`id_Pacientes`)
    REFERENCES `clinicadental2`.`tbl_Pacientes` (`id_Pacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicadental2`.`tbl_Piezas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental2`.`tbl_Piezas` (
  `id_Piezas` INT NOT NULL AUTO_INCREMENT,
  `nombrePieza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Piezas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicadental2`.`tbl_Presupuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental2`.`tbl_Presupuestos` (
  `id_Presupuesto` INT NOT NULL AUTO_INCREMENT,
  `id_Piezas` INT NOT NULL,
  `id_Pacientes` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`id_Presupuesto`),
  INDEX `fk_tbl_Presupuestos_tbl_Piezas1_idx` (`id_Piezas` ASC),
  INDEX `fk_tbl_Presupuestos_tbl_Pacientes1_idx` (`id_Pacientes` ASC),
  CONSTRAINT `fk_tbl_Presupuestos_tbl_Piezas1`
    FOREIGN KEY (`id_Piezas`)
    REFERENCES `clinicadental2`.`tbl_Piezas` (`id_Piezas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Presupuestos_tbl_Pacientes1`
    FOREIGN KEY (`id_Pacientes`)
    REFERENCES `clinicadental2`.`tbl_Pacientes` (`id_Pacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicadental2`.`tratamientoRealizar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental2`.`tratamientoRealizar` (
  `id_Seguimientos` INT NOT NULL AUTO_INCREMENT,
  `id_Citas` INT NOT NULL,
  `id_Presupuesto` INT NOT NULL,
  `tratamientoRealizar` VARCHAR(1000) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Pagado` FLOAT NOT NULL,
  PRIMARY KEY (`id_Seguimientos`),
  INDEX `fk_tbl_Seguimientos_tbl_Citas1_idx` (`id_Citas` ASC),
  INDEX `fk_tbl_Seguimientos_tbl_Presupuestos1_idx` (`id_Presupuesto` ASC),
  CONSTRAINT `fk_tbl_Seguimientos_tbl_Citas1`
    FOREIGN KEY (`id_Citas`)
    REFERENCES `clinicadental2`.`tbl_Citas` (`id_Citas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_Seguimientos_tbl_Presupuestos1`
    FOREIGN KEY (`id_Presupuesto`)
    REFERENCES `clinicadental2`.`tbl_Presupuestos` (`id_Presupuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
